# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: pscode
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fetchuser
# "service" is the name of this project. This will also be added to your AWS resource names.
service: fetch-user

provider:
  name: aws
  runtime: nodejs20.x

functions:
  fetchuser:
    handler: handler.fetchUser
    events:
      - httpApi:
          path: /
          method: get
